version: '3.7'
services:
  db:
    container_name: praha-challenge-postgresql
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - praha-challenge-postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: praha-challenge-postgresql
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"

  app:
    depends_on:
      - db
    container_name: praha-challenge-app
    tty: true
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app

volumes:
  praha-challenge-postgresql:
    driver: local
